

<nav class="navbar navbar-inverse bg-faded">
  <a class="navbar-brand" href="#">3della</a>
  <ul class="nav navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="<?php echo $this->baseUrl('index.php/admin')?>">Home</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="<?php echo $this->baseUrl('index.php/users')?>">Users</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="<?php echo $this->baseUrl('index.php/categories')?>">Categories</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="<?php echo $this->baseUrl('index.php/forums')?>">Forums</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="<?php echo $this->baseUrl('index.php/threads')?>">Threads</a>
    </li>
    
    <li class="nav-item">
      <a class="nav-link" href="<?php echo $this->baseUrl('index.php/users/logout')?>">logout</a>
    </li>

  </ul>
  <ul class="nav navbar-nav navbar-right">
	  <li class="nav-item">
	  	<img src='<?php echo $this->baseUrl("/static/img/admin.png")?>' height='50px'>
	  </li>
	  <li class="nav-item padding-10">
		  <a class="nav-link" href="<?php echo $this->baseUrl('index.php/threads')?>">Logout</a>
	  </li>
  </ul>

</nav>
