<br><br>
<footer class="navbar navbar-inverse" id="footer">
	Zend Forums project developed by an ITI team copyrights @2017
	<img src="<?php echo $this->baseUrl('static/img/facebook.png')?>" class="facebook_img"
	width="20" height="20"/>
	<img src="<?php echo $this->baseUrl('static/img/instagram.png')?>" width="20" height="20"/>
	<img src="<?php echo $this->baseUrl('static/img/twitter.png')?> " class="img-circle" width="20" height="20"/>
</footer>
