

<nav class="navbar navbar-inverse bg-faded">
  <a class="navbar-brand" href="#">3della</a>
  <ul class="nav navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="<?php echo $this->baseUrl()?>">Home <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="<?php echo $this->baseUrl('index.php/users')?>">Users</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="<?php echo $this->baseUrl('index.php/categories')?>">Categories</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="<?php echo $this->baseUrl('index.php/forums')?>">Forums</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="<?php echo $this->baseUrl('index.php/threads')?>">Threads</a>
    </li>
    
    <li class="nav-item">
      <a class="nav-link" href="<?php echo $this->baseUrl('index.php/users/logout')?>">logout</a>
    </li>


  </ul>

</nav>
