

<nav class="navbar navbar-inverse bg-faded">
  <a class="navbar-brand" href="<?php echo $this->baseUrl('/')?>">3deella</a>
  <ul class="nav navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="<?php echo $this->baseUrl('index.php/users/edit/id/')?>">Profile</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="<?php echo $this->baseUrl('index.php/threads/userThreads')?>">MyThreads</a>
    </li>
    <li class="nav-item">
      <img src="<?php ?>" />
    </li>
  </ul>
  <ul class="nav navbar-nav navbar-right">
	  <li class="nav-item">
		  <img src='<?php echo $this->baseUrl($this->identity->image)?>' height='50px'>
		
	  </li>
	  <li class="nav-item padding-10">
		  <a class="nav-link" href="<?php echo $this->baseUrl('index.php/users/logout')?>">Logout</a>
	  </li>
  </ul>

</nav>
