<!DOCTYPE html>
<html>
	<head>
		<title>My Fourm</title>
		<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/static/css/bootstrap.css">
		<link rel="stylesheet" href="<?php echo $this->baseUrl()?>/static/css/style.css">
		<script src='<?php echo $this->baseUrl()?>/static/js/jquery-2.2.0.min.js'></script>
		<script src='<?php echo $this->baseUrl()?>/static/js/bootstrap.js'></script>
		<script src='<?php echo $this->baseUrl()?>/static/js/script.js'></script>
	</head>
	<body>
		<?php echo $this->partial('_header.phtml'); ?>
		<div class="container">
		<?php echo $this->layout()->content; ?>
		</div>
		<?php echo $this->partial('_footer.phtml'); ?>
	</body>
</html>
