<!DOCTYPE html>
<html>
	<head>
		<title>My Fourm</title>
		<link rel="stylesheet" href="<?php echo $this->baseUrl("/static/css/bootstrap.css")?>">
		<link rel="stylesheet" href="<?php echo $this->baseUrl("/static/css/style.css")?>">
		<script src='<?php echo $this->baseUrl("/static/js/jquery-2.2.0.min.js")?>'></script>
		<script src='<?php echo $this->baseUrl("/static/js/bootstrap.js")?>'></script>
		<script src='<?php echo $this->baseUrl("/static/js/script.js")?>'></script>
	</head>
	<body>
		<?php
		if (!isset($this->identity)) {
		?>

			<nav class="navbar navbar-inverse bg-faded">
			  <a class="navbar-brand" href="<?php echo $this->baseUrl('/')?>">3deella</a>
			  <ul class="nav navbar-nav">

				<li class="nav-item">
				  <a class="nav-link" href="<?php echo $this->baseUrl('index.php/users/add')?>">Register</a>
				</li>
			  </ul>
			  <ul class="nav navbar-nav navbar-right">
				 <li class="nav-item padding-10">
					 <a class="nav-link" href="<?php echo $this->baseUrl('index.php/users/login')?>">Login</a>
				 </li>
			  </ul>

			</nav>

		<?php
		}
		elseif ($this->identity->is_admin) {
		?>

			<nav class="navbar navbar-inverse bg-faded">
			<div class="navbar-header">
			  <a class="navbar-brand" href="<?php echo $this->baseUrl('/')?>">3deella</a>
			  <ul class="nav navbar-nav">
				<li class="nav-item">
				  <a class="nav-link" href="<?php echo $this->baseUrl('index.php/admin')?>">Home</a>
				</li>
				<li class="nav-item">
				  <a class="nav-link" href="<?php echo $this->baseUrl('index.php/users')?>">Users</a>
				</li>
				<li class="nav-item">
				  <a class="nav-link" href="<?php echo $this->baseUrl('index.php/categories')?>">Categories</a>
				</li>
				<li class="nav-item">
				  <a class="nav-link" href="<?php echo $this->baseUrl('index.php/forums')?>">Forums</a>
				</li>
				<li class="nav-item">
				  <a class="nav-link" href="<?php echo $this->baseUrl('index.php/threads')?>">Threads</a>
				</li>

			  </ul>
			  <ul class="nav navbar-nav navbar-right">
				  <li class="nav-item">
					<img src='<?php echo $this->baseUrl("/static/img/admin.png")?>' height='50px'>
				  </li>
				  <li class="nav-item padding-10">
					  <a class="nav-link" href="<?php echo $this->baseUrl('index.php/users/logout')?>">Logout</a>
				  </li>
			  </ul>

			</div>
			</nav>

		<?php
		}
		else {
		?>


			<nav class="navbar navbar-inverse bg-faded">
			  <a class="navbar-brand" href="<?php echo $this->baseUrl('/')?>">3deella</a>
			  <ul class="nav navbar-nav">
			    <li class="nav-item">

			      <a class="nav-link" href='<?php echo $this->baseUrl("index.php/users/edit/id/". $this->identity->id )?>'>Profile</a>
			    </li>
			    <li class="nav-item">
			      <a class="nav-link" href="<?php echo $this->baseUrl('index.php/home/uthreads/id/'. $this->identity->id)?>">MyThreads</a>
			    </li>
			    <li class="nav-item">
			      <img src="<?php ?>" />
			    </li>
			  </ul>
			  <ul class="nav navbar-nav navbar-right">
				  <li class="nav-item">
					  <img src='<?php echo $this->baseUrl($this->identity->image)?>' height='50px'>

				  </li>
				  <li class="nav-item padding-10">
					  <a class="nav-link" href="<?php echo $this->baseUrl('index.php/users/logout')?>">Logout</a>
				  </li>
			  </ul>

			</nav>

		<?php
		}

		?>


		<div class="container">
		<?php echo $this->layout()->content; ?>
		</div>
		<?php echo $this->partial('_footer.phtml'); ?>
	</body>
</html>
