<br /><br />




 <a href="<?php echo $this->baseUrl('/index.php/threads/add')?>">
 <button class="btn btn-primary">Add thread </button>
 </a>

<br><br>

<table class="table">
	<thead>
		<th>id</th>
		<th>title</th>
		<th>body</th>
		<th>date &amp; time</th>
		<th>is sticky</th>
		<th>is opened</th>
		<th>forum </th>
		<th>user id</th>
		<th>category </th>
		<th>actions</th>
	</thead>

	<?php
		if ($this->threads) {
			# code...
			for ($i=0; $i <count($this->threads) ; $i++) {
				# code...
				echo "<tr>";
				echo "<td>".$this->threads[$i]['id']."</td>";
				echo "<td>".$this->threads[$i]['title']."</td>";

				if ( strlen($this->threads[$i]['body']) > 40) {
				echo "<td>". substr($this->threads[$i]['body'],0, 40 ) ." .... </td>";
				}else{
					echo "<td>". $this->threads[$i]['body'] ."</td>";
				}

				//echo "<td>".$this->threads[$i]['body']."</td>";
				echo "<td>".$this->threads[$i]['date']."</td>";
				if ($this->threads[$i]['is_sticky'] == 1) {
					# code...
					echo "<td>"."sticky"."</td>";
				}else{
					echo "<td>"."--"."</td>";
				}

				if ($this->threads[$i]['is_opened'] == 1) {
					# code...
					echo "<td>"."--"."</td>";
				}else{
					echo "<td>"."closed"."</td>";
				}
				echo "<td>"./*$this->threads[$i]['forum_id'] */$this->forums[$i]['forum']."</td>";
				echo "<td>"./*$this->threads[$i]['user_id']*/ $this->users[$i]['username']."</td>";
																			// ['username'] da men 3and el controller mesh 3and el database
				echo "<td>"./*$this->threads[$i]['category_id']*/$this->categories[$i]['category']."</td>";


				echo "<td><a class='btn btn-danger' href='".$this->baseUrl("index.php/threads/delete/id/").$this->threads[$i]['id']."'>delete</a>";
				echo "<td> <a class='btn btn-info' href='". $this->baseUrl("index.php/threads/edit/id/". $this->threads[$i]['id']) . "' > Edit </a> ";
				echo "</td>";
				echo "</tr>";
			}

		}
	?>
</table>


<?php
/*
if($this->threads) {



	for($i=0; $i<count($this->threads); $i++){

		echo"<div class='panel panel-default'>";
	    echo "<div class='panel-heading'> thread no. ".$this->threads[$i]['id']."</div>";
	    echo "<div class='panel-body'>";
	    echo "</div>";

		echo "<table border=1 class='table table-striped'>" ;
		//echo '<tr><td> Id: '.$this->threads[$i]['id'].'</td></tr>';
		echo '<tr><td>title: '.$this->threads[$i]['title'].'</td></tr>';
		echo '<tr><td>text: '.$this->threads[$i]['body'].'</td></tr>';
		echo '<tr><td> <a  href="'.$this->baseUrl().'/index.php/blog-x/delete/id/'.$this->threads[$i]['id'].'"> <button class="btn btn-danger" >Delete</button> </a>';
		echo '<a href="'.$this->baseUrl().'/index.php/blog-x/edit/id/'.$this->threads[$i]['id'].'"><button class="btn btn-primary"> Edit </button></a>';

		echo '<a href="'.$this->baseUrl().'/index.php/blog-x/details/id/'.$this->threads[$i]['id'].'"><button class="btn btn-success"> more details </button></a></td></tr>';

		echo "</tr>";
		//echo str_repeat('*', 100).'<br />';
		echo "</table>";

		echo "</div>";

		echo "<br>";
	}



}

*/

?>
