<br /><br />

<a class='btn btn-info' href="<?php echo $this->baseUrl()?>/index.php/forums/add"> Add Forums </a>
<br><br>
<table class="table">
    <thead>
       
        <th>name</th>
       <th>descreption</th> 
      <th>is_opened</th>
      <th>category</th>
      <th>action</th>
    </thead>

<?php
    if($this->forums) {
        for($i=0; $i< count($this->forums); $i++) {
            echo "<tr>";
            echo "<td>". $this->forums[$i]['name'] ."</td>";
            echo "<td>". $this->forums[$i]['descreption'] ."</td>";
            echo "<td>". $this->forums[$i]['is_opened'] ."</td>";
             echo "<td>". $this->forums[$i]['category'] ."</td>";

            echo "<td> <a class='btn btn-info' href='". $this->baseUrl() ."/index.php/forums/edit/id/". $this->forums[$i]['id'] ."' > Edit </a> ";
            echo "<a class='btn btn-danger' href='". $this->baseUrl() ."/index.php/forums/delete/id/". $this->forums[$i]['id'] ."' > Delete </a></td>";
            echo "<tr>";
        }
    }

?>

</table>
