<br /><br />


<?php
//var_dump($this->threads);
echo " <br> <br>" ;
//var_dump($this->categories);
echo " <br> <br>" ;
//var_dump($this->forums);
?>

<?php


	if($this->categories) {

		for($i=0; $i<count($this->categories); $i++){

			echo"<div class='panel panel-default'>";
		    echo "<div class='panel-heading center'>  ".$this->categories[$i]['name']."</div>";
		    echo "<div class='panel-body'>";


			echo "<table class='table table-striped center'>" ;
			echo "<thead>";
			echo "<th class='center'>forum name</th>";
			echo "<th class='center'>Descreption</th>";
			echo "<th class='center'>No. of Threads</th>";
			echo "</thead>";
			for ($j=0; $j < count($this->categories[$i]['forums']) ; $j++) {
				echo "<tr>";
				echo "<td><a href='".$this->baseUrl()."/index.php/home/forum/id/".$this->categories[$i]['forums'][$j]['id']."'>". $this->categories[$i]['forums'][$j]['name'] ."</a></td>";

				echo "<td>". $this->categories[$i]['forums'][$j]['descreption'] ."</td>";
				echo "<td>". $this->categories[$i]['forums'][$j]['threads_count'] ."</td>";
				echo"</tr>";
			}
			echo "</table>";

			echo "</div>";


			echo "</div>";
			echo "<br>";
		}

	}
